services:
  # 1. Tự động tải và chạy Database MySQL bản chuẩn
  mysql-db:
    image: mysql:8.0.43-debian
    container_name: dekiru-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data_hub:/var/lib/mysql

  # 2. Tự động tải và chạy Redis
  redis:
    image: redis:7
    container_name: dekiru-redis
    ports:
      - "6379:6379"

  # 3. Chạy Backend (Hỗ trợ cả Build từ code hoặc tải trực tiếp Image từ Docker Hub)
  backend:
    build:
      context: ./dekiru
      dockerfile: Dockerfile
    image: kienvanbau/satapp-backend:2.0
    container_name: dekiru-backend-local
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      - redis
    environment:
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

volumes:
  mysql_data_hub:
